
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class ParametrSetCommand
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ParametrSetCommand()
    {

        this.Name = "";

        this.Invert = false;

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public int Cooldown { get; set; }

    public bool Invert { get; set; }



    public virtual Parameter DestParameter { get; set; }

    public virtual Parameter SrcParameter1 { get; set; }

    public virtual Sensor Sensor { get; set; }

    public virtual Parameter SrcParameter2 { get; set; }

    public virtual Reaction Reaction { get; set; }

}

}
