
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class Parameter
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Parameter()
    {

        this.Name = "";

        this.ComandParameterLinks = new HashSet<ComandParameterLink>();

        this.TemplateParameters = new HashSet<TemplateParameter>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Value { get; set; }

    public int ParameterTypeId { get; set; }

    public bool IsPublic { get; set; }

    public byte[] Image { get; set; }

    public Nullable<int> NextParameterId { get; set; }

    public string Description { get; set; }

    public string ButtonDescription { get; set; }



    public virtual ParameterType ParameterType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ComandParameterLink> ComandParameterLinks { get; set; }

    public virtual ParameterCategory ParameterCategory { get; set; }

    public virtual Sensor Sensor { get; set; }

    public virtual Parameter NextParameter { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TemplateParameter> TemplateParameters { get; set; }

}

}
