
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class SensorType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SensorType()
    {

        this.MinValue = 0;

        this.MaxValue = 0;

        this.Sensors = new HashSet<Sensor>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Key { get; set; }

    public int MinValue { get; set; }

    public int MaxValue { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sensor> Sensors { get; set; }

}

}
