
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class Template
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Template()
    {

        this.TemplateParameters = new HashSet<TemplateParameter>();

        this.TemplateSensors = new HashSet<TemplateSensor>();

        this.TemplatedDevicePairs = new HashSet<TemplatedDevicePair>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public int TemplateType { get; set; }

    public int TemplateMode { get; set; }

    public bool IsActive { get; set; }



    public virtual Scenario Scenario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TemplateParameter> TemplateParameters { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TemplateSensor> TemplateSensors { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TemplatedDevicePair> TemplatedDevicePairs { get; set; }

}

}
